env:
  global:
    - CONAN_REFERENCE: "libtiff/4.0.8"
    - CONAN_CHANNEL: "stable"
    - CONAN_UPLOAD: "https://api.bintray.com/conan/zamazan4ik/conan"
    - CONAN_STABLE_BRANCH_PATTERN: "release/*"
    - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker
osx: &osx
  os: osx
  language: generic

matrix:
  include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.6 CONAN_DOCKER_IMAGE=lasote/conangcc46
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.8 CONAN_DOCKER_IMAGE=lasote/conangcc48        
      - <<: *linux
        env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.2 CONAN_DOCKER_IMAGE=lasote/conangcc52
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.3 CONAN_DOCKER_IMAGE=lasote/conangcc53        
      - <<: *linux
        env: CONAN_GCC_VERSIONS=5.4 CONAN_DOCKER_IMAGE=lasote/conangcc54
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.2 CONAN_DOCKER_IMAGE=lasote/conangcc62        
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6.3 CONAN_DOCKER_IMAGE=lasote/conangcc63
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7.1 CONAN_DOCKER_IMAGE=lasote/conangcc71        
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.8 CONAN_DOCKER_IMAGE=lasote/conanclang38        
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40
      - <<: *osx
        osx_image: xcode7.0
        env: CONAN_APPLE_CLANG_VERSIONS=7.0
      - <<: *osx
        osx_image: xcode7.3
        env: CONAN_APPLE_CLANG_VERSIONS=7.3
      - <<: *osx
        osx_image: xcode8.2
        env: CONAN_APPLE_CLANG_VERSIONS=8.0
      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
